# Project Name
TARGET = RTT

# Sources
ASMPP_SOURCES = vendor/SEGGER_RTT_ASM_ARMv7M.S
C_SOURCES = vendor/SEGGER_RTT.c vendor/SEGGER_RTT_printf.c
CPP_SOURCES = RTT.cpp 

# Library Locations
LIBDAISY_DIR = ../..

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
